version: '2.4'
services:
  cloudmapper:
    build: .
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - ACCOUNT_ID
      - ACCOUNT_NAME
    ports:
      - "8000:8000"
    volumes:
      - "cloudmapper-web:/opt/cloudmapper/web"
    command: ["--webserver"]

volumes:
  cloudmapper-web:
